development:
  dialect: postgres
  datasource: host=${POSTGRES_HOST} dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} sslmode=disable
  dir: migrations

test:
  dialect: postgres
  datasource: host=${POSTGRES_HOST} dbname=${POSTGRES_TEST_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} sslmode=disable
  dir: migrations