# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
  server:
    build: build/debug/server
    ports:
      - "8888:8888"
    volumes:
      - .:/go/src/app
    env_file:
      - build/debug/server/.env